### ISSUE TITLE
Move aggregates to openfisca-survey-manager

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-plugin-aggregates#7]
Rationale:
- reduce the number of projects to maintain separately
- create a generic aggregate object together with a generic build_aggregates survey_scenario method
- customize the latter method for openfisca-france and openfisca-france-indirect-taxation

@adrienpacifico what do you think ?

**Comment by adrienpacifico** [comment]
Well, 
> reduce the number of projects to maintain separately

I do agree on that one ; also, we might have to think about the big picture of how things are articulated. I'm not sure about it (and I don't have better solution for now), but it might not be the most easy and efficient way to do.

> create a generic aggregate object together with a generic build_aggregates survey_scenario method

I'm not sure enough about how things are working right now to comment on that. How is it working right now ? To what extent a generic aggregate object would be better than a specific one ? If it increases the complication of the code, is there really big pros ?

**Comment by benjello** [comment]
They have been moved to openfisca-france-data
